<?php

@require_once (drupal_get_path('module', 'subsites') . '/subsites.class.inc');
@require_once (drupal_get_path('module', 'subsites') . '/subsites.helpers.inc');
@require_once (drupal_get_path('module', 'subsites') . '/subsites.blockvis.inc');

/**
 * Implements hook_permission().
 */
function subsites_permission()
{
	$permission = array();
	$permission['administer subsites'] = array(
		'title' => t('Administer subsites'),
		'description' => t('Perform administration tasks for this module. Only give this permission to trustable people.'),
	);
	$permission['view subsites'] = array('title' => t('View subsites'));
	$permission['assign content to subsites'] = array('title' => t('Assign content to subsites'));

	return $permission;
}

/**
 * Implements hook_menu().
 */
function subsites_menu()
{
	$items = array();

	/**
	 * Menu Tabs
	 */
	$items['admin/structure/subsites/list'] = array(
		'title' => 'List subsites',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -10,
	);
	$items['admin/structure/subsites/add'] = array(
		'title' => 'Add subsite',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('subsites_info_form'),
		'access arguments' => array('administer subsites'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'subsites.admin.inc',
	);

	/**
	 * Subsite Dashboard
	 */
	$items['admin/structure/subsites'] = array(
		'title' => 'Subsites',
		'description' => 'Configure and manage your subsite settings.',
		'page callback' => 'subsites_admin_dashboard',
		'access arguments' => array('view subsites'),
		'file' => 'subsites.admin.inc',
	);

	/**
	 * Individual Subsite Settings
	 */
	$items['admin/structure/subsites/%'] = array(
		'title' => 'Edit',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'subsites_info_form',
			3
		),
		'access arguments' => array('administer subsites'),
		'file' => 'subsites.admin.inc',
	);
	$items['admin/structure/subsites/%/delete'] = array(
		'title' => 'Delete subsite',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'subsites_delete_confirm_form',
			3
		),
		'access arguments' => array('administer subsites'),
		'file' => 'subsites.admin.inc',
	);

	return $items;
}

/**
 * Implements hook_custom_theme().
 */
function subsites_custom_theme()
{
	$subsite = Subsite::getCurrent();
	$custom_theme = null;

	if ($subsite != null)
	{
		// add css file
		drupal_add_css($subsite -> css);

		// switch to custom theme, this will only take effect if theme is active
		// to prohibit a destroyed site
		$custom_theme = $subsite -> theme;
	}
	else
	{
		$subsite = (object) array(
			'sid' => -1,
			'name' => t('Main site')
		);
	}

	// set context
	if (module_exists('context'))
	{
		if ($plugin = context_get_plugin('condition', 'subsites'))
		{
			$plugin -> execute($subsite);
		}
	}

	return $custom_theme;
}

/**
 * Loads the options for the themes select form element.
 */
function getThemeOptions($add_default = TRUE)
{
	$options = array();

	if ($add_default)
	{
		$options[-1] = '<' . t('System default') . '>';
	}

	foreach (list_themes() as $key => $theme)
	{
		$options[$theme -> name] = t('@name (@status)', array(
			'@name' => $theme -> name,
			'@status' => ($theme -> status ? t('Enabled') : t('Disabled'))
		));
	}

	return $options;
}
